#!/bin/bash
# For the version with no IO/traps
#exec pdftk A=old\ LC-3\ Reference\ Sheet.pdf B=tom-ref.pdf cat A1 B1 output LC-3\ Reference\ Sheet.pdf

# The file `LC-3 Reference Sheet_redux.pdf' more mopier-friendly and is generated by printing to a PDF in Evince
exec pdftk A=old\ LC-3\ Reference\ Sheet.pdf B=tom-ref-w-traps-io.pdf cat A1 B1 output LC-3\ Reference\ Sheet.pdf
